config/routes.rb
Blog::Application.routes.draw do


  ###################
  ## Legacy Routes ##
  ###################
  get "author/ihid" => redirect("/blog")

  get "category/*subcategory" => redirect("/blog")

  get "page/2" => redirect("/blog")

  get "2011/03" => redirect("/blog")
  get "2011/05" => redirect("/blog")
  get "2011/06" => redirect("/blog")
  get "2012/01" => redirect("/blog")
  get "2012/02" => redirect("/blog")

  get "about_me" => redirect("/pages/about")

  get "blog/creating-an-ec2-webserver-using-amazon-s-basic-ami--2" => redirect("blog/creating-an-ec2-webserver-using-amazon-s-basic-ami")
  get "removing-duplicate-code-by-using-blocks-in-ruby" => redirect("/blog")
  get "having-a-hobby-project" => redirect("/blog")
  get "blog/schema.org" => redirect("/blog/markup-your-blog-using-schema-org")
  get "blog/search" => redirect("/blog")

  get "projects/national_rail" => redirect("/projects/national-rail-api")
  get "projects/email_tracker" => redirect("/pages/email-tracker")
  get "author/ihid/page/2/" => redirect("/")
  get "blog/search" => redirect("/blog")
  get "blog.." => redirect("/blog")
  get "email_tracker" => redirect("/projects/email-tracker")

  {
    "a-scope-for-returning-no-records-in-activerecord" => "a-scope-for-returning-no-records-in-activerecord",
    "allow-escape_attrs-on-a-per-tag-basis-in-haml" => "allow-escape_attrs-on-a-per-tag-basis-in-haml",
    "highly-targeted-advertising-on-ruby-forum-com" => "highly-targeted-advertising-on-ruby-forum-com",
    "ranges-not-accepted-for-form-select-tags-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",
    "bug-in-rails-3-2-activerecord-store-typeerror-cant-convert-symbol-into-integer" => "bug-in-rails-3-2-activerecord-store-typeerror-can-t-convert-symbol-into-integer",
    "rubygems-1-8-2-broke-my-rake" => "rubygems-1-8-2-broke-my-rake",
    "bug-in-rails-3-1-when-setting-table_name-when-using-multiple-namespaces" => "bug-in-setting-table_name-when-using-multiple-namespaces",
    "creating-an-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect" => "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect",
    "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight" => "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight",
    "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1" => "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1",
    "belongs_to_enum-is-released" => "belongs_to_enum-is-released",
    "testing-views-with-rails-3-rspec-2-and-webrat" => 'testing-views-with-rails-3-rspec-2-and-webrat',
    "haml-is-broken-with-partial-layouts" => "haml-is-broken-with-partial-layouts",
    "creating-a-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "form-select-tag-does-not-accept-ranges-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",

    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated",
    "blog/backbone-js-coffeescript-jasm" => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",
    "blog/backbone-js-coffeescript-jasmine-haml-and-rails-..." => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",

    "blog/rails-update_attribute-is-deprecated" => "rails-update_attribute-is-deprecated-from-3-2-7",
    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated-from-3-2-7"
    }.each do |old_url, blog_post_title|
    get old_url => redirect("/blog/#{blog_post_title}")
    get "#{old_url}/feed" => redirect("/blog/#{blog_post_title}")
  end

  get "pages" => redirect("/")

  ##########################
  ## End of Legacy Routes ##
  ##########################

  namespace :admin do
    resource :session
    resources :blog_images
    resources :blog_posts do
      put :publish, on: :member
    end
    resources :blog_comments do
      put :verify, on: :member
    end
  end
  resources :blog_posts, path: 'blog' do
    resources :blog_comments
  end

  resources :projects
  get "sitemap" => "pages#sitemap"
  get "about" => "pages#about"
  get "speaking" => "pages#speaking"
  get "writing" => "pages#writing"
  get "open_source" => "pages#open_source"

  root :to => 'pages#index'

end

app/views/pages/about.html.haml
.prose
    %h2 About Me
    %h3 Introduction
    %p I'm a #{my_age_in_years} year old geek from Birmingham, England who can normally be found working on my laptop in one of the various coffeshops around the city. Online, I am known as #{link_to "iHiD", "http://twitter.com/iHiD"}.
    %p
        I offset the hours I spend in front of a screen by playing lots of sport. I play football (soccer for the Americans) and I climb reguarly. I used to play Ultimate Frisbee, serving as the president of the University of Birmingham team and played for UTB (Ultimate Team Birmingham), captaining them in 2005 in the top division. I once held the world record for the longest ever game of Ultimate.
    %p
        I am the
        %span{style:"word-wrap:normal"} co-founder
        and CTO of New Media Education where I manage several projects including #{link_to "Meducation", "https://www.meducation.net"} - a social education network for doctors and medical students, #{link_to "Ordino", "http://www.ordinoapp.com"} - a tool for organising your education and #{link_to "The Medical Search", "http://themedicalsearch.com"} - a search engine for medical professionals.
    %p I'm passionate about open source and lot of what we do at New Media is released under open source licences, including the popular #{link_to "Propono", "http://meducation.github.io/propono"} library. I also contribute to other open source projects where I can (including #{link_to "Rails", "https://github.com/rails/rails/commits/master?author=ihid"}, #{link_to "Foreigner", "https://github.com/matthuhiggins/foreigner/commits/master?author=ihid"}, #{link_to "HAML", "https://github.com/nex3/haml"} and #{link_to "Kronic", "https://github.com/xaviershay/kronic/commits/master?author=ihid"}) and have from time to time been involved with helping Katrina Owen on the excellent #{link_to "Exercism.io", "http://exercism.io"} project.

    %p I eat and socialise at #{link_to "Monday Night Pie Night", "http://www.mondaynightpienight.com"}.

    %h3 I'm a Geek
    %p
        I have been programming since the age of 8, originally writing games in AMOS for the Amiga. I have a degree in
        %em Computer Science &amp; Artificial Intelligence
        and have been writing commercial applications since 2004.
    %p
        I have been building web applications in
        %em Ruby on Rails Rails since 2005
        and have a deep understanding of both Ruby and the Rails framework. I am comfortable with the full web stack -
        %em Linux web servers,
        server-side technologies such as
        %em SQL
        and
        %em memcache,
        and client-side technologies such as
        %em CoffeeScript,
        %em jQuery
        and
        %em Ember.js.
    %p
        I have written large embedded desktop applications in
        %em C#
        iPhone apps in
        %em Objective C, and dabbled with Android.
        I am familiar with a wide variety of other languages (my university final year project was in PHP) and have a strong interest in Artificial Intelligence.

    %h3 An Entrepreneur
    %p I have always been someone to carve my own path in life.
    %P I quit my day job in 2008, founding a software development company. A year later, I co-founded #{link_to "Meducation", "https://www.meducation.net"}, a social education network for medics, with my long-term friend #{link_to "Dr Alastair Buick", "http://twitter.com/albuick"}. I stopped taking new clients in my first company in 2010 and started working full time on Meducation, which continues to grow from strength to strength.

app/views/pages/home.html.haml
%h2 Hello
%h2 Projects
-@projects.each do |project|
    %h3= link_to project.name, project

app/views/pages/index.html.haml
.prose
    %h2 Welcome!
    %p Hey there. I'm Jeremy Walker, a software developer and entrepreneur from sunny England. I am the co-founder and CTO of #{link_to "Meducation", "https://www.meducation.net"}. I am known online as #{link_to "iHiD", "http://twitter.com/iHiD"}.
    %p I maintain several #{link_to "open source projects", projects_path} including #{link_to "Propono", "http://meducation.github.io/propono"}, #{link_to "Larva", "http://meducation.github.io/larva"}, #{link_to "Super STI", "http://github.com/iHiD/super_sti"}, #{link_to "Loquor", "http://meducation.github.io/loquor"} and #{link_to "Inquisitio", "http://meducation.github.io/inquisitio"}. I'm also a contributor to the amazing #{link_to "Exercism.io", "http://exercism.io"}.
    %p I write technical posts on #{link_to "on my blog", blog_posts_path} and as a #{link_to "guest writer for other sites", "/writing"}. If you would like me to write for you, please contact me.
    %p You can follow me on #{link_to "Twitter", "https://twitter.com/ihid"}, check out my work on #{link_to "Github", "http://github.com/ihid"} or contact me #{link_to "via email", "mailto:jez.walker@gmail.com"}.

%a.twitter-timeline{href:"https://twitter.com/iHiD", "data-widget-id" => "296995136372609024"} Tweets by @iHiD
:javascript
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/pages/open_source.html.haml
.prose
    %h2 Open Source
    %p I'm passionate about open source and try to contribute to OS projects wherever possible. A lot of the code that is written at my company is released under open source licences.

    %p Here are some of the projects that I maintain:

    %ul#projects
        %li
            = link_to "Propono", "http://meducation.github.io/propono"
            \- The popular pub/sub Ruby library built on AWS.
        %li
            = link_to "Larva", "http://meducation.github.io/larva"
            \- A wrapper around Propono for quickly building services in an SOA.
        %li
            = link_to "Inquisitio", "http://meducation.github.io/inquisitio"
            \- An ActiveRecord-style wrapper around AWS Cloudsearch
        %li
            = link_to "Loquor", "http://meducation.github.io/loquor"
            \- A library giving an ActiveRecord-style interface to RESTful API calls.
        %li
            = link_to "Filum", "http://meducation.github.io/filum"
            \- A simple logging Library for Ruby that adds a consistent context id through log messages.
        %li
            = link_to "Super STI", "http://github.com/iHiD/super_sti"
            \- A set of improvements to Rails built in STI support.
        %li
            = link_to "Ember Infinite Pagination", "https://github.com/iHiD/ember-infinite-pagination"
            \- A popular infinite pagination solution for Ember
        %li
            = link_to "belongs_to_enum", "https://github.com/iHiD/belongs_to_enum" 
            \- Enum Support for Rails (Now build into Rails 4)
        %li
            = link_to "National Rail JSON API", "https://github.com/iHiD/national_rail"
            \- A resful JSON API wrapper built on top of the National Rail SOAP API
        %li
            = link_to "Rails Email Tracker", "https://github.com/iHiD/email_tracker"
            \- A gen for tracking emails in Rails applications.

    %p You can find the source code for all of these and many other projects on #{link_to "Github", "https://github.com/iHiD"}.

    %p I have also contributed to projects that I do not maintain, such as #{link_to "Rails", "https://github.com/rails/rails/commits/master?author=ihid"}, #{link_to "Foreigner", "https://github.com/matthuhiggins/foreigner/commits/master?author=ihid"}, #{link_to "HAML", "https://github.com/nex3/haml"} and #{link_to "Kronic", "https://github.com/xaviershay/kronic/commits/master?author=ihid"}). When I get the chance I help Katrina Owen on the excellent #{link_to "Exercism.io", "http://exercism.io"} project.

app/views/pages/personal.html.haml
%h2 Who Am I?
%h3 A Person
%p 
    I'm a #{my_age_in_years} year old guy from Birmingham, England. I'm married to the beautiful #{link_to "Liz", "http://twitter.com/#!/serethia"} and I am the technical 
    %span{style:"word-wrap:normal"} co-founder 
    of #{link_to "Meducation", "https://www.meducation.net"}. I can normally be found working on my laptop in one of the various Starbucks around the city. I love sport and play football three times a week. I used to play Ultimate Frisbee, and was president of them University of Birmingham team and played UTB (Ultimate Team Birmingham), captaining them in 2005 in the A tour. I eat and socialise at #{link_to "Monday Night Pie Night", "http://www.mondaynightpienight.com"}.

%h3 A Geek
%p 
    I have been programming since the age of 12, original writing games for my Amiga in Basic. I have a degree in 
    %em Computer Science & Artificial Intelligence
    and have been writing production applications since 2004.
%p 
    I have been writing web applications in 
    %em Rails since 2005 
    and have a deep understanding of both Ruby and the Rails framework. I am comfortable with the full web stack - 
    %em Linux web servers,
    server-side technologies such as 
    %em SQL
    and 
    %em memcache,
    and client-side technologies such as 
    %em Coffeescript,
    %em JQuery
    and 
    %em Backbone.
%p 
    I have written large embedded desktop applications in 
    %em C# 
    and an iPhone app in
    %em Objective C. 
    I am familiar with a wide variety of other languages (my university final year project was in <em>PHP</em>) and have a strong interest in Artificial Intelligence.
%p
    I am a big believer in 
    %em open source
    and have contributed to various projects including #{link_to "Rails", "http://github.com/rails/rails"}, #{link_to "Foreigner", "https://github.com/matthuhiggins/foreigner"}, #{link_to "HAML", "https://github.com/nex3/haml"} and #{link_to "Kronic", "https://github.com/xaviershay/kronic"}. I have several #{link_to "public repositories on Github", "http://github.com/ihid"} and maintain two gems: #{link_to "super_sti", "http://rubygems.org/gems/super_sti"} and #{link_to "belongs_to_enum", "http://rubygems.org/gems/belongs_to_enum"}.

%h3 An Entrepreneur
%p I have always wanted to carve my own path in life and make my mark on the world.
%P I quit my day job in 2008, founding a software development company. A year later, I co-founded #{link_to "Meducation", "https://www.meducation.net"}, a social educational network for medics, with my long-term friend #{link_to "Dr Alastair Buick", "http://twitter.com/albuick"}. I wound down my first company in 2010 and started working full time on Meducation, which continues to grow from strength to strength.

app/views/pages/sitemap.xml.haml
!!! XML
%urlset{"xmlns" => "http://www.sitemaps.org/schemas/sitemap/0.9", "xmlns:image" => "http://www.google.com/schemas/sitemap-image/1.1"}

    =sitemap_url_tag(root_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(about_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(speaking_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(about_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(writing_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(open_source_path, Date.new(2014, 07, 13), "monthly", "1")
    =sitemap_url_tag(blog_posts_path, Date.new(2014, 07, 13), "monthly", "1")

    -@blog_posts.each do |blog_post|
        =sitemap_url_tag(blog_post_url(blog_post), blog_post.updated_at, "weekly", "1")

app/views/pages/speaking.html.haml
.prose
    %h2 Conference Speaking
    %p I am an international conference speaker and MC (the person who introduces speakers, makes announcements and keeps the crowd interested when the inevitable technical issues occur).
    %p I have a confident, funny*, knowledgeable, and passionate style and love engaging with large crowds. I also enjoy MCing conferences and thrive on the pressure of keeping everything running smoothly. If you'd like to see me speaking, my talk on #{link_to "Refactoring your Productivity", "https://www.youtube.com/watch?v=utO5d56LA0s"} from Baruco 2013 is available online.
    %p If you would like me to be involved with yours, #{link_to "let me know", "mailto:jez.walker@gmail.com"}!
    %p
        %em.small * Clearly a matter of opinion.
    =image_tag("speaking.jpg", class:'image', alt: "Jeremy Walker (iHiD) speaking at Frozen Rails")
    .image_credit Speaking at Frozen Rails 2012. Photo by #{link_to "Maxim Filatov", "https://plus.google.com/101500913881556971089/posts?banner=pwa"}.

-#
    %h3 Talks I Have Given
    %h4.title How to be a Productive Developer
    %p My first talk, given at the Frozen Rails conference, on how to be a more productive developer. A humorous, yet informative talk with a specific focus on Ruby and Rails developers.
    %p Developing software can be an incredibly exciting, but also very challenging occupation. We can easily become bogged down in what we are doing, or feel overwhelmed by the challenges we face. This interesting, fun talk looks at how we can to get the most from our days and what we can do to keep enjoying writing software, even when it gets tough.
    %p A special thanks to #{link_to "Zed Shaw", "http://twitter.com/zedshaw"} for his material that I referenced, and to #{link_to "Steve Klabnik", "http://twitter.com/steveklabnik"} for being a great sport and counter-trolling me so expertly!
    %ul 
        %li= link_to "Slides from Frozen Rails", "http://www.speakerdeck.com/u/ihid/p/how-to-be-a-productive-developer"
        %li= link_to "Reaction From Frozen Rails", image_path("tweets/frozen_rails_2012.png")
    -#
        %h3 Upcoming Conferences
        %table 
            %colgroup
                %col{style: 'width:250px'}
                %col{style: 'width:180px'}
                %col
            %tr
                %th Conference
                %th Date
                %th Talk
            %tr
                %td= link_to "Digital Doctor Conference", "http://www.lanyrd.com/2012/digidoc"
                %td December 7<sup>th</sup> 2012
                %td TBC

        %h3 Previous Conferences
        %table 
            %colgroup
                %col{style: 'width:250px'}
                %col{style: 'width:180px'}
                %col
            %tr
                %th Conference
                %th Date
                %th Talk
            %tr
                %td= link_to "Frozen Rails 2012", "http://www.lanyrd.com/2012/frozenrails"
                %td September 21<sup>st</sup> 2012
                %td How to be a Productive Developer 

app/views/pages/writing.html.haml
.prose
    %h2 Writing
    %p As well as writing on my blog, I also write as a guest author for other websites. Here are some articles that have been published on other website:
    %ul 
        %li
            = link_to "Propono - Pub/Sub for Ruby", "http://www.sitepoint.com/propono-pubsub-ruby/"
            \ - Written for SitePoint.
        %li
            =link_to "Backbone.js, Coffeescript, Jasmine, Haml and Rails working together", "http://www.ihid.co.uk/blog/backbone-js-coffeescript-jasmine-haml-and-rails-working-together"
            \- Featured in
            #{link_to "Ruby Weekly", "http://rubyweekly.com"},
            #{link_to "Javascript Weekly", "http://javascriptweekly.com"} 
            and on
            #{link_to "Ruby5", "http://ruby5.envylabs.com/episodes/279-episode-275-may-25th-2012/stories/2453-getting-started-with-jasmine"}
        %li
            = link_to "Techniques To Secure Your Website With Ruby on Rails (Part 1)", "http://www.sitepoint.com/techniques-to-secure-your-website-with-ruby-on-rails-part-1"
            \ - Written for SitePoint.
        %li
            = link_to "Techniques To Secure Your Website With Ruby on Rails (Part 2)", "http://www.sitepoint.com/techniques-to-secure-your-website-with-ruby-on-rails-part-2"
            \ - Written for SitePoint.
        %li
            = link_to "Techniques To Secure Your Website With Ruby on Rails (Part 3)", "http://www.sitepoint.com/techniques-to-secure-your-website-with-ruby-on-rails-part-3"
            \ - Written for SitePoint.
        %li
            =link_to "Markup Your Blog Using schema.org", "http://www.ihid.co.uk/blog/markup-your-blog-using-schema-org"

    %h3 Would you like a guest author?
    %p I'd love to write for your website/magazine etc. Please #{link_to "contact me", "mailto:jez.walker@gmail.com"} if you're interested.