config/routes.rb
Blog::Application.routes.draw do


  ###################
  ## Legacy Routes ##
  ###################
  get "author/ihid" => redirect("/blog")

  get "category/*subcategory" => redirect("/blog")

  get "page/2" => redirect("/blog")

  get "2011/03" => redirect("/blog")
  get "2011/05" => redirect("/blog")
  get "2011/06" => redirect("/blog")
  get "2012/01" => redirect("/blog")
  get "2012/02" => redirect("/blog")

  get "about_me" => redirect("/pages/about")

  get "blog/creating-an-ec2-webserver-using-amazon-s-basic-ami--2" => redirect("blog/creating-an-ec2-webserver-using-amazon-s-basic-ami")
  get "removing-duplicate-code-by-using-blocks-in-ruby" => redirect("/blog")
  get "having-a-hobby-project" => redirect("/blog")
  get "blog/schema.org" => redirect("/blog/markup-your-blog-using-schema-org")
  get "blog/search" => redirect("/blog")

  get "projects/national_rail" => redirect("/projects/national-rail-api")
  get "projects/email_tracker" => redirect("/pages/email-tracker")
  get "author/ihid/page/2/" => redirect("/")
  get "blog/search" => redirect("/blog")
  get "blog.." => redirect("/blog")
  get "email_tracker" => redirect("/projects/email-tracker")

  {
    "a-scope-for-returning-no-records-in-activerecord" => "a-scope-for-returning-no-records-in-activerecord",
    "allow-escape_attrs-on-a-per-tag-basis-in-haml" => "allow-escape_attrs-on-a-per-tag-basis-in-haml",
    "highly-targeted-advertising-on-ruby-forum-com" => "highly-targeted-advertising-on-ruby-forum-com",
    "ranges-not-accepted-for-form-select-tags-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",
    "bug-in-rails-3-2-activerecord-store-typeerror-cant-convert-symbol-into-integer" => "bug-in-rails-3-2-activerecord-store-typeerror-can-t-convert-symbol-into-integer",
    "rubygems-1-8-2-broke-my-rake" => "rubygems-1-8-2-broke-my-rake",
    "bug-in-rails-3-1-when-setting-table_name-when-using-multiple-namespaces" => "bug-in-setting-table_name-when-using-multiple-namespaces",
    "creating-an-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect" => "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect",
    "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight" => "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight",
    "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1" => "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1",
    "belongs_to_enum-is-released" => "belongs_to_enum-is-released",
    "testing-views-with-rails-3-rspec-2-and-webrat" => 'testing-views-with-rails-3-rspec-2-and-webrat',
    "haml-is-broken-with-partial-layouts" => "haml-is-broken-with-partial-layouts",
    "creating-a-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "form-select-tag-does-not-accept-ranges-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",

    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated",
    "blog/backbone-js-coffeescript-jasm" => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",
    "blog/backbone-js-coffeescript-jasmine-haml-and-rails-..." => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",

    "blog/rails-update_attribute-is-deprecated" => "rails-update_attribute-is-deprecated-from-3-2-7",
    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated-from-3-2-7"
    }.each do |old_url, blog_post_title|
    get old_url => redirect("/blog/#{blog_post_title}")
    get "#{old_url}/feed" => redirect("/blog/#{blog_post_title}")
  end

  get "pages" => redirect("/")

  ##########################
  ## End of Legacy Routes ##
  ##########################

  namespace :admin do
    resource :session
    resources :blog_images
    resources :blog_posts do
      put :publish, on: :member
    end
    resources :blog_comments do
      put :verify, on: :member
    end
  end
  resources :blog_posts, path: 'blog' do
    resources :blog_comments
  end

  resources :projects
  get "sitemap" => "pages#sitemap"
  get "about" => "pages#about"
  get "speaking" => "pages#speaking"
  get "writing" => "pages#writing"
  get "open_source" => "pages#open_source"

  root :to => 'pages#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  extend FriendlyId
  
  attr_accessible :title, :content, :published_at
  friendly_id :title, use: [:slugged, :history]
  
  has_many :comments, class_name: "BlogComment", order: "id ASC"
  
  scope :published, where("published_at IS NOT NULL")
  
  def is_published?
    !!published_at
  end
  
  def publish!
    update_attribute(:published_at, DateTime.now)
  end
  
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < AdminController
  
  def index
    @blog_posts = BlogPost.all
  end
  
  def show
    @blog_post = BlogPost.find(params[:id])
  end
  
  def new
    @blog_post = BlogPost.new
    setup_form
  end
  
  def create
    @blog_post = BlogPost.new(params[:blog_post])
    if @blog_post.save
      redirect_to [:admin, @blog_post]
    else
      setup_form
      render action: 'new'
    end
  end
  
  def edit
    @blog_post = BlogPost.find(params[:id])
    setup_form
  end
  
  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update_attributes(params[:blog_post])
      redirect_to [:admin, @blog_post]
    else
      setup_form
      render action: 'edit'
    end
  end
  
  def publish
    @blog_post = BlogPost.find(params[:id])
    @blog_post.publish!
    redirect_to [:admin, @blog_post]
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to admin_blog_posts_path
  end  

  private
  
  def setup_form
    @blog_images = BlogImage.all
  end
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.published.order("published_at desc")
    @metadata[:title] = "Blog"
  end

  def show
    @blog_post = BlogPost.find(params[:id])
    @metadata[:title] = @blog_post.title
    raise ActiveRecord::RecordNotFound unless @blog_post.is_published?

    @metadata[:title] = "#{@blog_post.title} by Jeremy Walker"
  end

end

app/helpers/admin/blog_posts_helper.rb
module Admin::BlogPostsHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/admin/blog_posts/_form.html.haml
=form_for [:admin, @blog_post], html: {class:"admin_blog_post_form"} do |f|
    =f.label :title, "Title"
    =f.text_field :title

    =f.label :content, "Content"
    =f.text_area :content

    =f.submit
    
%h3 Images
=render "admin/blog_images/images"
=render "admin/blog_images/new"

app/views/admin/blog_posts/edit.html.haml
=render "form"

app/views/admin/blog_posts/index.html.haml
%h2 Blog Posts
%h3 New Post
=button_to "Create New Post", new_admin_blog_post_path, method: :get

%h3 Existing Posts
%table 
    %tr
        %th Id
        %th Title
        %th Comments
        %th{colspan:3} Options
        
    -@blog_posts.each do |blog_post|
        %tr
            %td= blog_post.id
            %td= blog_post.title
            %td= blog_post.comments.count
            %td
                -if blog_post.is_published?
                    =link_to "View", blog_post
                -else
                    =link_to "View", [:admin, blog_post]
            %td= link_to "Edit", edit_admin_blog_post_path(blog_post)
            %td= link_to "Delete", admin_blog_post_path(blog_post), method: :delete, confirm:"You really want to delete this?" 

app/views/admin/blog_posts/new.html.haml
=render "form"

app/views/admin/blog_posts/show.html.haml
.admin_blog_post_info
    
    -if @blog_post.is_published?
        %h3 This post has been published.
        =link_to "Edit Post", edit_admin_blog_post_path(@blog_post)
    -else
        %h3 This post has NOT been published!
        =link_to "Edit Post", edit_admin_blog_post_path(@blog_post)
        &#183;
        =link_to "Publish Post", publish_admin_blog_post_path(@blog_post), confirm: "Publish Post?", method: :put
    

#blog_post
    %h2= @blog_post.title
    -if @blog_post.is_published?
        .date Written on #{@blog_post.published_at.strftime("%A %b #{@blog_post.published_at.day.ordinalize} %Y")}
    .content
        =raw @blog_post.content