config/routes.rb
Blog::Application.routes.draw do


  ###################
  ## Legacy Routes ##
  ###################
  get "author/ihid" => redirect("/blog")

  get "category/*subcategory" => redirect("/blog")

  get "page/2" => redirect("/blog")

  get "2011/03" => redirect("/blog")
  get "2011/05" => redirect("/blog")
  get "2011/06" => redirect("/blog")
  get "2012/01" => redirect("/blog")
  get "2012/02" => redirect("/blog")

  get "about_me" => redirect("/pages/about")

  get "blog/creating-an-ec2-webserver-using-amazon-s-basic-ami--2" => redirect("blog/creating-an-ec2-webserver-using-amazon-s-basic-ami")
  get "removing-duplicate-code-by-using-blocks-in-ruby" => redirect("/blog")
  get "having-a-hobby-project" => redirect("/blog")
  get "blog/schema.org" => redirect("/blog/markup-your-blog-using-schema-org")
  get "blog/search" => redirect("/blog")

  get "projects/national_rail" => redirect("/projects/national-rail-api")
  get "projects/email_tracker" => redirect("/pages/email-tracker")
  get "author/ihid/page/2/" => redirect("/")
  get "blog/search" => redirect("/blog")
  get "blog.." => redirect("/blog")
  get "email_tracker" => redirect("/projects/email-tracker")

  {
    "a-scope-for-returning-no-records-in-activerecord" => "a-scope-for-returning-no-records-in-activerecord",
    "allow-escape_attrs-on-a-per-tag-basis-in-haml" => "allow-escape_attrs-on-a-per-tag-basis-in-haml",
    "highly-targeted-advertising-on-ruby-forum-com" => "highly-targeted-advertising-on-ruby-forum-com",
    "ranges-not-accepted-for-form-select-tags-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",
    "bug-in-rails-3-2-activerecord-store-typeerror-cant-convert-symbol-into-integer" => "bug-in-rails-3-2-activerecord-store-typeerror-can-t-convert-symbol-into-integer",
    "rubygems-1-8-2-broke-my-rake" => "rubygems-1-8-2-broke-my-rake",
    "bug-in-rails-3-1-when-setting-table_name-when-using-multiple-namespaces" => "bug-in-setting-table_name-when-using-multiple-namespaces",
    "creating-an-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect" => "iphone-error-the-user-name-or-password-for-imap-gmail-com-is-incorrect",
    "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight" => "why-ed-miliband-not-ken-clarke-should-be-apologising-tonight",
    "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1" => "fixed-foreigner-gem-to-work-with-reversing-migrations-in-rails-3-1",
    "belongs_to_enum-is-released" => "belongs_to_enum-is-released",
    "testing-views-with-rails-3-rspec-2-and-webrat" => 'testing-views-with-rails-3-rspec-2-and-webrat',
    "haml-is-broken-with-partial-layouts" => "haml-is-broken-with-partial-layouts",
    "creating-a-ec2-webserver-using-amazons-basic-ami" => "creating-an-ec2-webserver-using-amazon-s-basic-ami",
    "form-select-tag-does-not-accept-ranges-in-rails-3-2" => "form-select-tag-does-not-accept-ranges-in-rails-3-2",

    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated",
    "blog/backbone-js-coffeescript-jasm" => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",
    "blog/backbone-js-coffeescript-jasmine-haml-and-rails-..." => "backbone-js-coffeescript-jasmine-haml-and-rails-working-together",

    "blog/rails-update_attribute-is-deprecated" => "rails-update_attribute-is-deprecated-from-3-2-7",
    "blog/rails-update_attribute-is-depreciated" => "rails-update_attribute-is-deprecated-from-3-2-7"
    }.each do |old_url, blog_post_title|
    get old_url => redirect("/blog/#{blog_post_title}")
    get "#{old_url}/feed" => redirect("/blog/#{blog_post_title}")
  end

  get "pages" => redirect("/")

  ##########################
  ## End of Legacy Routes ##
  ##########################

  namespace :admin do
    resource :session
    resources :blog_images
    resources :blog_posts do
      put :publish, on: :member
    end
    resources :blog_comments do
      put :verify, on: :member
    end
  end
  resources :blog_posts, path: 'blog' do
    resources :blog_comments
  end

  resources :projects
  get "sitemap" => "pages#sitemap"
  get "about" => "pages#about"
  get "speaking" => "pages#speaking"
  get "writing" => "pages#writing"
  get "open_source" => "pages#open_source"

  root :to => 'pages#index'

end

app/views/layouts/admin.html.haml
-content_for :content do
    =stylesheet_link_tag :admin
    #admin
        =yield
    
=render :template => 'layouts/application'

app/views/layouts/application.html.haml
!!! 5
%html
    %head
        %title= html_title
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Euphoria+Script', media: 'all'
        = stylesheet_link_tag '//f.fontdeck.com/s/css/o6QfaKWxqPEublQOv9rluKl/2c4/www.ihid.co.uk/42127.css', media: 'all'
        = csrf_meta_tags

        %meta{name:"google-site-verification", content:"6VD3DtSnJfVMNRAmWeFIhecUhhllVaJsjnwxQu2ac6w"}

        =canonical_link
        %link{rel:"shortcut icon", href:image_path('favicon.ico')}

    %body

        %header{itemscope:'', itemtype:'http://schema.org/WPHeader'}
            %h1
                = link_to root_path do
                    =image_tag "header_image.jpg", id: "header_image"
                    .name Jeremy Walker
            = link_to "Software Developer & Social Entrepreneur", root_path, class: 'tagline'

        %nav
            .container
                = link_to "Home", root_path
                = link_to "About", about_path
                = link_to "Open Source", open_source_path
                = link_to "Blog", blog_posts_path
                = link_to "Writing", writing_path
                = link_to "Speaking", speaking_path

        %main
            =content_for?(:content) ? yield(:content) : yield

        %footer{itemscope:'', itemtype:'http://schema.org/WPFooter'}
            .container
                &copy; Jeremy Walker (iHiD) 2005 - 2014
                .powered_by Site designed and created by #{link_to "iHiD", "http://www.ihid.co.uk"}.

        =javascript_include_tag "application"

        :javascript
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-17313109-2']);
            _gaq.push(['_setDomainName', 'ihid.co.uk']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        =javascript_include_tag "http://code.jquery.com/jquery-2.1.1.min.js"
        :javascript
            $(window).scroll(function () {
                fix = $(window).scrollTop() > $('header').outerHeight();
                console.log(fix);

                if(fix) {
                    $("body").addClass("fixed-nav");
                }
                else {
                    $("body").removeClass("fixed-nav");
                }
            });

        %script{src:"http://yandex.st/highlightjs/6.2/highlight.min.js"}
        %link{rel:"stylesheet", href:"http://yandex.st/highlightjs/6.2/styles/github.min.css"}
        %script
            hljs.showLineNumbers = true;
            hljs.stripEmptyLines = true;
            hljs.initHighlightingOnLoad();

        %script{type:"text/javascript", src:"http://w.sharethis.com/button/buttons.js"}
        :javascript
            stLight.options({publisher: "12d6b158-bc08-4e54-bd03-bddc4d7beaba", doNotHash: true, doNotCopy: true, hashAddressBar: false});

app/views/layouts/project.html.haml
-content_for :content do
    #project
        =link_to "View on Github", @project.github_url, class: "repository_url"
        %h2= @project.descriptive_name
        .description= @project.description

        =yield
    
=render :template => 'layouts/application'